services:
  dernek-postgres:
    image: postgres:latest
    container_name: dernek-postgres-compose
    restart: always
    environment:
      POSTGRES_DB: dernek_db
      POSTGRES_USER: dernek_user
      POSTGRES_PASSWORD: dernek123
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data # Named volume kullan
      - ./init-db:/docker-entrypoint-initdb.d # Init scriptleri için
    networks:
      - dernek-network

  redis-server:
    image: redis:latest
    container_name: redis-server-compose
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      - dernek-network

volumes:
  postgres-data: # Named volume - herkes aynı isimleri kullanacak
  redis-data:


networks:
  dernek-network:
    driver: bridge
