services:
  dernek-postgres:
    image: postgres:latest
    container_name: dernek-postgres-compose
    restart: always
    environment:
      POSTGRES_DB: dernek_db
      POSTGRES_USER: dernek_user
      POSTGRES_PASSWORD: dernek123
    ports:
      - "5432:5432"
    volumes:
      - C:\docker-data\postgres:/var/lib/postgresql/data
    networks:
      - dernek-network

  redis-server:
    image: redis:latest
    container_name: redis-server-compose
    restart: always
    environment:
      REDIS_PASSWORD: mypassword123
      REDIS_ARGS: --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      - dernek-network

volumes:
  redis-data:
    external: true

networks:
  dernek-network:
    driver: bridge
